alias reload='source ~/.profile'

# up 'n' folders
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# git commamands simplified
alias gst='git status'
alias gco='git checkout'
alias gci='git commit -a -m'
alias grb='git rebase'
alias gbr='git branch'

# docker
alias docker-start='docker-machine start default'
alias docker-env='eval "$(docker-machine env default)"'
alias docker-stop='docker-machine stop default'
alias docker-pr='docker run -i -t -v ~/docker-mnt:/mnt/vol -v ~/workspace:/opt silviaterra/general bash'
alias docker-sequoia='docker run -i -t -v ~/docker-mnt:/mnt/vol -v ~/workspace:/opt silviaterra/sequoia bash'

# dev aliases
alias web='cd ~/workspace/st_web; workon st_web'
alias mrt='cd ~/workspace/mr_t; workon mr-t'
alias update='for repo in ~/workspace/*; do cd $repo && git pull; done'
