alias reload='source ~/.profile'

# up 'n' folders
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# git commamands simplified
alias gst='git status'
alias gco='git checkout'
alias gci='git commit -a -m'
alias grb='git rebase'
alias gbr='git branch'

# dev aliases
alias web='cd ~/workspace/st_web; workon st_web'
alias mrt='cd ~/workspace/mr_t; workon mr-t'
alias update='for repo in ~/workspace/*; do cd $repo && git pull; done'
